import requests, json

def get():
    obj = requests.get('https://api.adviceslip.com/advice')
    if obj.status_code != 200:
        return False
    else:
        # print(obj.status_code)
        mjson = json.loads(obj.text)
        for n in mjson.values():
            num = str(n['advice'])
            return num

def dolarget(fisrt, second):
    obj = requests.get(f'https://economia.awesomeapi.com.br/last/{fisrt}-{second}')
    print(obj.status_code)
    if obj.status_code != 200:
        return False
    else:
        obj1 = json.loads(obj.text)
        for i in obj1.values():
            a = [i['ask'], i['high'], i['low']]
            print(a)
            return a

choice = (
    #('AFN', 'Afghani do Afeganistão'),
    #('MGA','Ariary Madagascarense'),
    #('THB','Baht Tailandês'),
    #('PAB','Balboa Panamenho'),
    #('ETB', 'Birr Etíope'),
    ('BTC', 'Bitcoin'),
    ('BOB', 'Boliviano'),
    ('VEF', 'Bolívar Venezuelano'),
    ('XBR', 'Brent Spot'),
    ('GHS','Cedi Ganês'),
    ('SVC','Colon de El Salvador'),
    ('CRC','Colón Costarriquenho'),
    ('CZK','Coroa Checa'),
    ('DKK','Coroa Dinamarquesa'),
    ('ISK','Coroa Islandesa'),
    ('NOK','Coroa Norueguesa'),
    ('SEK','Coroa Sueca'),
    ('NIO','Córdoba Nicaraguense'),
    ('GMD','Dalasi da Gâmbia'),
    ('MKD','Denar Macedônio'),
    ('DZD','Dinar Argelino'),
    ('IQD','Dinar Iraquiano'),
    ('JOD','Dinar Jordaniano'),
    ('KWD','Dinar Kuwaitiano'),
    ('LYD','Dinar Líbio'),
    ('RSD','Dinar Sérvio'),
    ('TND','Dinar Tunisiano'),
    ('BHD','Dinar do Bahrein'),
    ('MAD','Dirham Marroquino'),
    ('AED','Dirham dos Emirados'),
    ('STD','Dobra São Tomé Príncipe'),
    ('DOGE','Dogecoin'),
    ('VND','Dong Vietnamita'),
    ('AMD','Dram Armênio'),
    ('USD','Dólar Americano'),
    ('AUD','Dólar Australiano'),
    ('CAD','Dólar Canadense'),
    ('JMD','Dólar Jamaicano'),
    ('NAD','Dólar Namíbio'),
    ('NZD','Dólar Neozelandês'),
    ('TWD','Dólar Taiuanês'),
    ('ZWL','Dólar Zimbabuense'),
    ('BSD','Dólar das Bahamas'),
    ('KYD','Dólar das Ilhas Cayman'),
    ('BBD','Dólar de Barbados'),
    ('BZD','Dólar de Belize'),
    ('BND','Dólar de Brunei'),
    ('SGD','Dólar de Cingapura'),
    ('FJD','Dólar de Fiji'),
    ('HKD','Dólar de Hong Kong'),
    ('TTD','Dólar de Trinidad'),
    ('XCD','Dólar do Caribe Oriental'),
    #('CVE','Escudo cabo-verdiano'),
    ('ETH','Ethereum'),
    ('EUR','Euro'),
    ('HUF','Florim Húngaro'),
    #('BIF','Franco Burundinense'),
    #('XAF', 'Franco CFA Central'),
    #('XOF','Franco CFA Ocidental'),
    #('XPF','Franco CFP'),
    #('KMF','Franco Comorense'),
    #('RWF','Franco Ruandês'),
    ('CHF','Franco Suíço'),
    ('CHFRTS','Franco Suíço'),
    ('GNF','Franco de Guiné'),
    ('DJF','Franco do Djubouti'),
    ('HTG','Gourde Haitiano'),
    ('PYG','Guarani Paraguaio'),
    ('ANG','Guilder das Antilhas'),
    ('UAH','Hryvinia Ucraniana'),
    ('JPY','Iene Japonês'),
    #('JPYRTS','Iene Japonês'),
    ('PGK','Kina Papua-Nova Guiné'),
    ('LAK','Kip Laosiano'),
    ('HRK','Kuna Croata'),
    ('MWK','Kwacha Malauiana'),
    ('ZMK','Kwacha Zambiana'),
    ('AOA','Kwanza Angolano'),
    ('MMK','Kyat de Mianmar'),
    ('GEL','Lari Georgiano'),
    ('ALL','Lek Albanês'),
    ('HNL','Lempira Hondurenha'),
    ('MDL','Leu Moldavo'),
    ('RON','Leu Romeno'),
    ('BGN','Lev Búlgaro'),
    ('EGP','Libra Egípcia'),
    ('GBP','Libra Esterlina'),
    ('LBP','Libra Libanesa'),
    ('SDG','Libra Sudanesa'),
    ('SYP','Libra Síria'),
    ('SZL','Lilangeni Suazilandês'),
    ('LTC','Litecoin'),
    ('LSL','Loti do Lesoto'),
    ('AZN','Manat Azeri'),
    ('BAM','Marco Conversível'),
    ('MZN','Metical de Moçambique'),
    ('MNT','Mongolian Tugrik'),
    ('NGN','Naira Nigeriana'),
    ('NGNI','Naira Nigeriana'),
    ('NGNPARALLEL', 'Naira Nigeriana'),
    ('TRY', 'Nova Lira Turca'),
    ('ILS', 'Novo Shekel Israelense'),
    ('MRO', 'Ouguiya Mauritana'),
    ('MOP', 'Pataca de Macau'),
    ('ARS', 'Peso Argentino'),
    ('CLP', 'Peso Chileno'),
    ('COP', 'Peso Colombiano'),
    ('CUP', 'Peso Cubano'),
    ('DOP', 'Peso Dominicano'),
    ('PHP', 'Peso Filipino'),
    ('MXN', 'Peso Mexicano'),
    ('UYU', 'Peso Uruguaio'),
    ('BWP', 'Pula de Botswana'),
    ('GTQ', 'Quetzal Guatemalteco'),
    ('ZAR', 'Rand Sul-Africano'),
    ('BRL', 'Real Brasileiro'),
    ('BRLT', 'Real Brasileiro Turismo'),
    ('QAR', 'Rial Catarense'),
    ('IRR', 'Rial Iraniano'),
    ('OMR', 'Rial Omanense'),
    ('KHR', 'Riel Cambojano'),
    ('MYR', 'Ringgit Malaio'),
    ('YER', 'Riyal Iemenita'),
    ('SAR', 'Riyal Saudita'),
    ('BYN', 'Rublo Bielorrusso'),
    ('RUB', 'Rublo Russo'),
    ('RUBTOM', 'Rublo Russo'),
    ('MVR','Rufiyaa Maldiva'),
    ('IDR','Rupia Indonésia'),
    ('INR','Rúpia Indiana'),
    ('MUR','Rúpia Mauriciana'),
    ('NPR','Rúpia Nepalesa'),
    ('PKR','Rúpia Paquistanesa'),
    ('LKR','Rúpia de Sri Lanka'),
    ('SCR','Rúpias de Seicheles'),
    ('KES','Shilling Queniano'),
    ('SOS','Shilling Somaliano'),
    ('TZS','Shilling Tanzaniano'),
    ('UGX','Shilling Ugandês'),
    ('PEN','Sol do Peru'),
    ('KGS','Som Quirguistanês'),
    ('UZS','Som Uzbequistanês'),
    ('TJS','Somoni do Tajiquistão'),
    ('BDT','Taka de Bangladesh'),
    ('KZT','Tengue Cazaquistanês'),
    ('VUV','Vatu de Vanuatu'),
    ('KRW','Won Sul-Coreano'),
    ('XAGG','XPrata'),
    ('CNY','Yuan Chinês'),
    ('CNH','Yuan chinês offshore'),
    ('PLN', 'Zlóti Polonês'),
)
